### ISSUE TITLE
Attempting to load a non-existent project crashes the server

### ISSUE THREAD

**Issue by ian-h-chamberlain** [steptools/StepNCViewer#84]
To recreate, start the server and attempt to load a project that doesn't exist:
Messages:

```
GET /stepnc/asdf 304 - - 125.858 ms
This project doesn't exist
Finder: no file open
GET /v2/nc/projects/asdf/workplan/ 500 1259 - 10.850 ms
TypeError: Cannot read property 'map' of undefined
    at exeFromId (/Users/ianchamberlain/step/StepNCViewer/src/server/api/v2/step.js:19:54)
    at _getMwp (/Users/ianchamberlain/step/StepNCViewer/src/server/api/v2/step.js:38:24)
    at Layer.handle [as handle_request] (/Users/ianchamberlain/step/StepNCViewer/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/ianchamberlain/step/StepNCViewer/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/ianchamberlain/step/StepNCViewer/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/ianchamberlain/step/StepNCViewer/node_modules/express/lib/router/layer.js:95:5)
    at /Users/ianchamberlain/step/StepNCViewer/node_modules/express/lib/router/index.js:277:22
    at param (/Users/ianchamberlain/step/StepNCViewer/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/ianchamberlain/step/StepNCViewer/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/ianchamberlain/step/StepNCViewer/node_modules/express/lib/router/index.js:410:3)
GET /v2/nc/projects/asdf/state/loop/ 304 - - 2.261 ms
Assertion failed: (val->IsString() == true), function Write, file ../src/string_bytes.cc, line 358.
This project doesn't exist

Process finished with exit code 134
```

**Comment by ian-h-chamberlain** [comment]
Partially fixed in #86 but needs better error checking
